# Generated by Django 3.2.12 on 2022-02-26 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thangks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thangks',
            name='author',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thangks',
            name='caption_1',
            field=models.TextField(blank=True, help_text='오늘 첫번째 감사한 내용을 적어주세요!'),
        ),
        migrations.AddField(
            model_name='thangks',
            name='caption_2',
            field=models.TextField(blank=True, help_text='오늘 두번째 감사한 내용을 적어주세요!'),
        ),
        migrations.AddField(
            model_name='thangks',
            name='caption_3',
            field=models.TextField(blank=True, help_text='오늘 세번째 감사한 내용을 적어주세요!'),
        ),
        migrations.AddField(
            model_name='thangks',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
