# Generated by Django 3.2.12 on 2022-02-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220213_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='teamchoice',
            field=models.CharField(blank=True, choices=[('남성 공동체', 'Male'), ('여성 공동체', 'Female'), ('젊은이 부', 'Young'), ('청소년부', 'Teenager'), ('아동부', 'Kids')], help_text='48px * 48px 크기의 png / jpg 파일을 업로드해주세요', max_length=6),
        ),
    ]
