# Generated by Django 3.2.12 on 2022-02-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220219_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_message',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
