# Generated by Django 3.2.12 on 2022-02-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='rema',
            field=models.TextField(blank=True, help_text='올해의 레마 말씀을 적어주세요!'),
        ),
    ]
