# Generated by Django 3.2.12 on 2022-02-19 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220219_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thangks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_1', models.TextField(blank=True, help_text='오늘 첫번째 감사한 내용을 적어주세요!')),
                ('caption_2', models.TextField(blank=True, help_text='오늘 두번째 감사한 내용을 적어주세요!')),
                ('caption_3', models.TextField(blank=True, help_text='오늘 세번째 감사한 내용을 적어주세요!')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
