# Generated by Django 3.2.12 on 2022-02-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_thangks_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thangks',
        ),
    ]
